#!/usr/bin/env python3
"""Build a theme-level coverage view for the machine-readable trend registry."""

from __future__ import annotations

import html
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = json.loads((ROOT / "manifests/us-trend-observation-schema-v1.json").read_text(encoding="utf-8"))
records = []
for path in sorted((ROOT / "analysis/records").glob("*.json")):
    data = json.loads(path.read_text(encoding="utf-8"))
    records.append({"path": path, "data": data, "count": len(data.get("observations", []))})

groups: dict[str, list[dict]] = defaultdict(list)
for record in records:
    for theme in record["data"].get("program_theme_ids", []):
        groups[theme].append(record)

def record_path(path: Path) -> str:
    return str(path.relative_to(ROOT / "analysis"))

md = [
    "# US trend-theme coverage",
    "",
    f"The current registry contains {len(records)} machine-readable records and {sum(r['count'] for r in records)} observations. This view groups them by the canonical 14-theme program inventory; counts are coverage controls, not evidence-quality scores.",
    "",
    "| Theme ID | Records | Observations | Evidence records |",
    "|---|---:|---:|---|",
]
for item in SCHEMA["program_theme_catalog"]:
    theme = item["id"]
    items = groups.get(theme, [])
    titles = "; ".join(f"[{r['data'].get('title', r['data'].get('trend_id', ''))}]({record_path(r['path'])})" for r in items)
    md.append(f"| `{theme}` ({item['title']}) | {len(items)} | {sum(r['count'] for r in items)} | {titles or 'No machine-readable record yet'} |")
md.extend([
    "",
    "## Reading rule",
    "",
    "A theme with many records is not necessarily better established: records may use different units, dates, denominators, and evidence types. A theme with no record remains a breadth gap. Cross-source convergence requires comparable units or an explicitly bounded comparison, not only a shared tag.",
    "",
    "Generated by `scripts/build_us_trend_theme_coverage.py` from `analysis/records/*.json`; validate the record inputs with `scripts/validate_trend_observation_records.py`.",
])
(ROOT / "analysis/us-trend-theme-coverage.md").write_text("\n".join(md) + "\n", encoding="utf-8")

cards = []
for item in SCHEMA["program_theme_catalog"]:
    theme = item["id"]
    items = groups.get(theme, [])
    links = "".join(f'<li><a href="../analysis/{html.escape(record_path(r["path"]), quote=True)}">{html.escape(r["data"].get("title", r["data"].get("trend_id", "")))}</a> ({r["count"]} observations)</li>' for r in items)
    cards.append(f'<article class="card"><p class="eyebrow">{html.escape(theme)}</p><h2>{html.escape(item["title"])}: {len(items)} records · {sum(r["count"] for r in items)} observations</h2><ul>{links or "<li>No machine-readable record yet.</li>"}</ul></article>')

style = ":root{--paper:#f5f3ed;--ink:#182c2a;--muted:#526560;--line:#cdd7cf;--accent:#155f51;--gold:#b96722}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:30px 24px 80px}a{color:var(--accent);text-underline-offset:4px}h1,h2{font-family:Georgia,serif;font-weight:normal;line-height:1.15}h1{font-size:clamp(2.6rem,6vw,4.8rem);max-width:850px;margin:38px 0 18px}h2{font-size:1.35rem;margin:8px 0 14px}.lede{font-size:1.2rem;max-width:840px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:25px}.card{background:#fffefa;border:1px solid var(--line);border-radius:10px;padding:24px}.eyebrow{font-size:.75rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent)}li{margin:8px 0}:focus-visible{outline:3px solid var(--gold);outline-offset:4px}@media(max-width:720px){main{padding:24px 16px}.grid{grid-template-columns:1fr}}"
html_doc = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>US trend-theme coverage</title><style>'+style+'</style></head><body><main><nav><a href="index.html">Research home</a> · <a href="us-trend-observations.html">Trend observations</a> · <a href="us-theme-atlas.html">Connections</a> / Theme coverage</nav><header><p class="eyebrow">Breadth control</p><h1>Which of the 14 program themes have measured trend objects?</h1><p class="lede">'+str(len(records))+' machine-readable records and '+str(sum(r["count"] for r in records))+' observations, grouped by the canonical 14-theme inventory. This is a coverage view, not a confidence score.</p></header><div class="grid">'+"".join(cards)+'</div><footer><p><a href="../analysis/us-trend-theme-coverage.md">Read Markdown edition</a> · <a href="us-trend-observations.html">Open trend registry</a></p></footer></main></body></html>'
(ROOT / "site/us-trend-theme-coverage.html").write_text(html_doc, encoding="utf-8")
print(f"Built trend-theme coverage for {len(SCHEMA['program_theme_catalog'])} program themes and {len(records)} records.")
