#!/usr/bin/env python3
"""Build the published index of machine-readable trend observations."""

from __future__ import annotations

import html
import json
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
RECORD_DIR = ROOT / "analysis/records"
records = []
for path in sorted(RECORD_DIR.glob("*.json")):
    data = json.loads(path.read_text(encoding="utf-8"))
    observations = data.get("observations", [])
    statuses = sorted({str(item.get("status", "unspecified")) for item in observations})
    records.append({
        "path": path,
        "data": data,
        "observations": observations,
        "statuses": statuses,
        "sources": sorted({urlsplit(str(item.get("source_url", ""))).netloc.lower().removeprefix("www.") for item in observations if item.get("source_url")}),
    })

if not records:
    raise SystemExit("No trend observation records found")

def md_path(path: Path) -> str:
    return str(path.relative_to(ROOT / "analysis"))

md = [
    "# US trend-observation registry",
    "",
    f"{len(records)} machine-readable trend records are published below. This is a reproducible observation index, not a claim that the atlas has a complete or causal trend for every theme.",
    "",
    "Each record preserves its source unit, geography, period-specific denominator, measure unit, method, uncertainty, subgroup scope, counterinterpretation, source URL, and retrieval or artifact hash. Read the boundary before comparing records.",
    "",
    "| Trend record | Umbrella IDs | Program theme IDs | Source unit | Geography | Observations | Periods | Statuses | Record |",
    "|---|---|---|---|---|---:|---|---|---|",
]
for record in records:
    data = record["data"]
    periods = "; ".join(str(item.get("period", "")) for item in record["observations"])
    statuses = "; ".join(record["statuses"])
    themes = ", ".join(data.get("theme_ids", []))
    program_themes = ", ".join(data.get("program_theme_ids", []))
    md.append(
        f"| {data.get('title', data.get('trend_id', ''))} | {themes} | {program_themes} | {data.get('source_unit', '')} | {data.get('geography', '')} | {len(record['observations'])} | {periods} | {statuses} | [open]({md_path(record['path'])}) |"
    )
    md.extend(["", f"**Boundary:** {data.get('boundary', '')}", ""])
md.extend([
    "## Interpretation rule",
    "",
    "A trend record is an evidence object, not a completed explanation. Observed or compared measures do not close arrows from material conditions to behavior, meaning, institutions, power, political action, or geopolitical consequence unless those stages are directly measured with a valid unit and timing.",
    "",
    "Generated by `scripts/build_us_trend_observation_registry.py`; validated by `scripts/validate_trend_observation_records.py`.",
])
(ROOT / "analysis/us-trend-observations.md").write_text("\n".join(md) + "\n", encoding="utf-8")

cards = []
all_statuses = sorted({status for record in records for status in record["statuses"]})
all_themes = sorted({theme for record in records for theme in record["data"].get("theme_ids", [])})
all_sources = sorted({source for record in records for source in record["sources"]})
SOURCE_LABELS = {
    "nber.org": "NBER",
    "bea.gov": "BEA",
    "bls.gov": "BLS",
    "census.gov": "US Census",
    "www2.census.gov": "US Census files",
    "federalreserve.gov": "Federal Reserve",
    "newyorkfed.org": "New York Fed",
    "financialresearch.gov": "OFR",
    "worldbank.org": "World Bank",
    "enterprisesurveys.org": "World Bank Enterprise Surveys",
    "imf.org": "IMF",
    "ilo.org": "ILO",
    "joint-research-centre.ec.europa.eu": "European Commission JRC",
    "publications.jrc.ec.europa.eu": "JRC Publications",
    "oecd.org": "OECD",
    "ers.usda.gov": "USDA ERS",
    "consumerfinance.gov": "CFPB",
    "ftc.gov": "FTC",
    "sipri.org": "SIPRI",
}
for record in records:
    data = record["data"]
    observations = record["observations"]
    periods = ", ".join(str(item.get("period", "")) for item in observations)
    links = sorted({str(item.get("source_url", "")) for item in observations if item.get("source_url")})
    source_links = " ".join(f'<a href="{html.escape(url, quote=True)}">source</a>' for url in links)
    measures = sorted({name for item in observations for name in item.get("measures", {})})
    themes = ", ".join(data.get("theme_ids", []))
    card = (
        f'<article class="card" data-search="{html.escape((data.get("title", "") + " " + data.get("trend_id", "") + " " + data.get("source_unit", "")).lower(), quote=True)}" data-status="{html.escape(" ".join(record["statuses"]), quote=True)}" data-themes="{html.escape(" ".join(data.get("theme_ids", [])), quote=True)}" data-sources="{html.escape(" ".join(record["sources"]), quote=True)}">'
        f'<p class="eyebrow">{html.escape(" · ".join(record["statuses"]))}</p>'
        f'<h2>{html.escape(data.get("title", data.get("trend_id", "")))}</h2>'
        f'<p><b>{len(observations)}</b> observations · {html.escape(data.get("source_unit", ""))} · {html.escape(data.get("geography", ""))}</p>'
        f'<p><b>Theme IDs:</b> {html.escape(themes)}</p>'
        f'<p><b>Periods:</b> {html.escape(periods)}</p>'
        f'<details><summary>Measures ({len(measures)})</summary><p>{html.escape(", ".join(measures))}</p></details>'
        f'<details><summary>Boundary</summary><p>{html.escape(data.get("boundary", ""))}</p></details>'
        f'<p><a href="../analysis/{html.escape(md_path(record["path"]), quote=True)}">Open record</a> · {source_links}</p></article>'
    )
    cards.append(card)

style = ":root{--paper:#f5f3ed;--ink:#182c2a;--muted:#526560;--line:#cdd7cf;--accent:#155f51;--gold:#b96722}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:30px 24px 80px}a{color:var(--accent);text-underline-offset:4px}h1,h2{font-family:Georgia,serif;font-weight:normal;line-height:1.15}h1{font-size:clamp(2.6rem,6vw,4.8rem);max-width:850px;margin:38px 0 18px}h2{font-size:1.4rem;margin:8px 0 14px}.lede{font-size:1.2rem;max-width:840px}.controls{position:sticky;top:0;background:var(--paper);padding:15px 0;border-bottom:1px solid var(--line);z-index:2}input{font:inherit;padding:12px;width:100%;border:1px solid #78938a;border-radius:6px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:25px}.card{background:#fffefa;border:1px solid var(--line);border-radius:10px;padding:24px}.eyebrow{font-size:.75rem;letter-spacing:.1em;text-transform:uppercase;color:var(--accent)}details{border-top:1px solid var(--line);padding:12px 0}summary{cursor:pointer;font-weight:600}[hidden]{display:none!important}:focus-visible{outline:3px solid var(--gold);outline-offset:4px}@media(max-width:720px){main{padding:24px 16px}.grid{grid-template-columns:1fr}}"
style += ".filter-row{display:grid;grid-template-columns:minmax(0,2fr) repeat(3,minmax(120px,1fr));gap:12px;align-items:end}.filter-row label{display:grid;gap:5px;font-weight:600;font-size:.9rem}.filter-row input,.filter-row select{font:inherit;padding:12px;border:1px solid #78938a;border-radius:6px;background:white}.filter-row button{font:inherit;padding:12px;border:1px solid var(--accent);border-radius:6px;background:var(--accent);color:white;cursor:pointer}.filter-row button:hover{background:#104b40}@media(max-width:900px){.filter-row{grid-template-columns:minmax(0,2fr) repeat(2,minmax(120px,1fr))}}@media(max-width:720px){.filter-row{grid-template-columns:1fr}}"
options_status = ''.join(f'<option value="{html.escape(status, quote=True)}">{html.escape(status.title())}</option>' for status in all_statuses)
options_theme = ''.join(f'<option value="{html.escape(theme, quote=True)}">{html.escape(theme.title())}</option>' for theme in all_themes)
options_source = ''.join(f'<option value="{html.escape(source, quote=True)}">{html.escape(SOURCE_LABELS.get(source, source))}</option>' for source in all_sources)
script = "const input=document.querySelector('#search'),status=document.querySelector('#status-filter'),theme=document.querySelector('#theme-filter'),source=document.querySelector('#source-filter'),clear=document.querySelector('#clear-filters'),cards=[...document.querySelectorAll('.card')],count=document.querySelector('#count');function apply(){const q=input.value.toLowerCase().trim(),s=status.value,t=theme.value,o=source.value;let n=0;cards.forEach(c=>{const show=(!q||c.dataset.search.includes(q))&&(!s||c.dataset.status.split(' ').includes(s))&&(!t||c.dataset.themes.split(' ').includes(t))&&(!o||c.dataset.sources.split(' ').includes(o));c.hidden=!show;if(show)n++});count.textContent=n+' of '+cards.length+' trend records shown'}[input,status,theme,source].forEach(control=>control.addEventListener('input',apply));clear.addEventListener('click',()=>{input.value='';status.value='';theme.value='';source.value='';apply();input.focus()});"
html_doc = (
    '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
    '<title>US trend observations</title><style>' + style + '</style></head><body><main>'
    '<nav><a href="index.html">Research home</a> · <a href="us-theme-atlas.html">Connections</a> · <a href="us-source-coverage.html">Source coverage</a> / Trend observations</nav>'
    '<header><p class="eyebrow">Machine-readable evidence layer</p><h1>What recurring observations are actually recorded?</h1>'
    f'<p class="lede">{len(records)} trend records across the current US-centered program. Each record keeps the denominator, method, uncertainty, subgroup, counterinterpretation, and boundary visible.</p></header>'
    f'<div class="controls"><div class="filter-row"><label>Find a record<input id="search" type="search" placeholder="Try financial, care, complaint or health"></label><label>Status<select id="status-filter"><option value="">All statuses</option>{options_status}</select></label><label>Theme<select id="theme-filter"><option value="">All themes</option>{options_theme}</select></label><label>Source<select id="source-filter"><option value="">All sources</option>{options_source}</select></label><button id="clear-filters" type="button">Clear filters</button></div><p id="count" role="status" aria-live="polite">{len(records)} of {len(records)} trend records shown</p></div>'
    '<div class="grid">' + "".join(cards) + '</div><footer><p><a href="../analysis/us-trend-observations.md">Read Markdown edition</a> · <a href="us-big-picture-synthesis.html">Read big-picture synthesis</a></p></footer><script>' + script + '</script></main></body></html>'
)
(ROOT / "site/us-trend-observations.html").write_text(html_doc, encoding="utf-8")
print(f"Built trend-observation registry for {len(records)} records.")
